export interface ThemePreset {
  name: string;
  description: string;
  tokens: Record<string, string>;
}

export const themePresets: Record<string, ThemePreset> = {
  light: {
    name: 'Light',
    description: 'Default light theme',
    tokens: {
      '--color-ink': '#1a1a1a',
      '--color-ink-2': '#6b6b6b',
      '--color-ink-3': '#9a9a9a',
      '--color-surface': '#ffffff',
      '--color-surface-field': '#f5f5f5',
      '--color-surface-canvas': '#fafafa',
      '--color-line': '#e5e5e5',
      '--color-line-strong': '#d1d1d1',
      '--color-accent': '#6366f1',
      '--color-green': '#22c55e',
      '--color-red': '#ef4444',
      '--color-orange': '#f97316',
      '--color-blue': '#3b82f6',
      '--color-purple': '#a855f7',
    },
  },
  dark: {
    name: 'Dark',
    description: 'Default dark theme',
    tokens: {
      '--color-ink': '#f5f5f5',
      '--color-ink-2': '#a3a3a3',
      '--color-ink-3': '#737373',
      '--color-surface': '#0a0a0a',
      '--color-surface-field': '#171717',
      '--color-surface-canvas': '#111111',
      '--color-line': '#2e2e2e',
      '--color-line-strong': '#404040',
      '--color-accent': '#818cf8',
      '--color-green': '#4ade80',
      '--color-red': '#f87171',
      '--color-orange': '#fb923c',
      '--color-blue': '#60a5fa',
      '--color-purple': '#c084fc',
    },
  },
  midnight: {
    name: 'Midnight',
    description: 'Deep blue/purple dark theme',
    tokens: {
      '--color-ink': '#e8e8f0',
      '--color-ink-2': '#9898b0',
      '--color-ink-3': '#6868808',
      '--color-surface': '#0c0c1d',
      '--color-surface-field': '#151530',
      '--color-surface-canvas': '#0a0a18',
      '--color-line': '#252548',
      '--color-line-strong': '#353560',
      '--color-accent': '#7c6ff7',
      '--color-green': '#34d399',
      '--color-red': '#fb7185',
      '--color-orange': '#fbbf24',
      '--color-blue': '#38bdf8',
      '--color-purple': '#a78bfa',
    },
  },
  sunset: {
    name: 'Sunset',
    description: 'Warm orange/amber accent theme',
    tokens: {
      '--color-ink': '#1c1917',
      '--color-ink-2': '#78716c',
      '--color-ink-3': '#a8a29e',
      '--color-surface': '#fffbf5',
      '--color-surface-field': '#fef3e2',
      '--color-surface-canvas': '#fefcf8',
      '--color-line': '#e7e0d6',
      '--color-line-strong': '#d6cec4',
      '--color-accent': '#ea580c',
      '--color-green': '#16a34a',
      '--color-red': '#dc2626',
      '--color-orange': '#d97706',
      '--color-blue': '#2563eb',
      '--color-purple': '#9333ea',
    },
  },
  forest: {
    name: 'Forest',
    description: 'Green/emerald nature theme',
    tokens: {
      '--color-ink': '#1a2e1a',
      '--color-ink-2': '#4a6a4a',
      '--color-ink-3': '#7a9a7a',
      '--color-surface': '#f5faf5',
      '--color-surface-field': '#e8f5e8',
      '--color-surface-canvas': '#f0f8f0',
      '--color-line': '#c8e0c8',
      '--color-line-strong': '#a8d0a8',
      '--color-accent': '#059669',
      '--color-green': '#15803d',
      '--color-red': '#dc2626',
      '--color-orange': '#ca8a04',
      '--color-blue': '#0284c7',
      '--color-purple': '#7c3aed',
    },
  },
  ocean: {
    name: 'Ocean',
    description: 'Cyan/teal water theme',
    tokens: {
      '--color-ink': '#0c1e2e',
      '--color-ink-2': '#4a6a80',
      '--color-ink-3': '#7a9aaa',
      '--color-surface': '#f0fafb',
      '--color-surface-field': '#e0f4f6',
      '--color-surface-canvas': '#f5fcfc',
      '--color-line': '#bce0e8',
      '--color-line-strong': '#94d0dc',
      '--color-accent': '#0891b2',
      '--color-green': '#14b8a6',
      '--color-red': '#e11d48',
      '--color-orange': '#ea580c',
      '--color-blue': '#0369a1',
      '--color-purple': '#7c3aed',
    },
  },
  monochrome: {
    name: 'Monochrome',
    description: 'Grayscale only, no color accents',
    tokens: {
      '--color-ink': '#171717',
      '--color-ink-2': '#525252',
      '--color-ink-3': '#a3a3a3',
      '--color-surface': '#ffffff',
      '--color-surface-field': '#f5f5f5',
      '--color-surface-canvas': '#fafafa',
      '--color-line': '#e5e5e5',
      '--color-line-strong': '#d4d4d4',
      '--color-accent': '#404040',
      '--color-green': '#525252',
      '--color-red': '#737373',
      '--color-orange': '#525252',
      '--color-blue': '#525252',
      '--color-purple': '#525252',
    },
  },
  'high-contrast': {
    name: 'High Contrast',
    description: 'WCAG AAA, thick borders, bold text',
    tokens: {
      '--color-ink': '#000000',
      '--color-ink-2': '#1a1a1a',
      '--color-ink-3': '#333333',
      '--color-surface': '#ffffff',
      '--color-surface-field': '#f0f0f0',
      '--color-surface-canvas': '#ffffff',
      '--color-line': '#000000',
      '--color-line-strong': '#000000',
      '--color-accent': '#0000cc',
      '--color-green': '#006600',
      '--color-red': '#cc0000',
      '--color-orange': '#cc6600',
      '--color-blue': '#0000cc',
      '--color-purple': '#6600cc',
    },
  },
};

export function applyTheme(el: HTMLElement, preset: ThemePreset) {
  for (const [key, value] of Object.entries(preset.tokens)) {
    el.style.setProperty(key, value);
  }
}
